from wizard_lm_guidance_prompts.add_doc_string import doc_string_guidance_prompt
from wizard_lm_guidance_prompts.add_type_hints import ADD_TYPE_HINTS
from wizard_lm_guidance_prompts.custom_prompt import CUSTOM_PROMPT
from wizard_lm_guidance_prompts.fix_syntax_error import FIX_SYNTAX_ERROR